'use strict';
const $=id=>document.getElementById(id);
const store={get(key,fallback=null){try{return JSON.parse(localStorage.getItem('rhone-'+key))??fallback;}catch{return fallback;}},set(key,value){try{localStorage.setItem('rhone-'+key,JSON.stringify(value));return true;}catch{return false;}}};
const places={balme:{name:'La Balme-les-Grottes',lat:45.852,lon:5.337},lyon:{name:'Lyon',lat:45.756,lon:4.84},morestel:{name:'Morestel',lat:45.675,lon:5.47}};
const stations=[{name:'Montluel',lat:45.8456,lon:5.0577,note:'Option près de Jons. La fiche ViaRhôna indique environ 7,3 km de Jons à la gare ; accès hors parcours à vérifier.'},{name:'La Valbonne',lat:45.8498,lon:5.1239,note:'Option dans la plaine de l’Ain. Étudier l’accès depuis le parcours et les trains vers Lyon.'},{name:'Ambérieu-en-Bugey',lat:45.9545,lon:5.342,note:'Option depuis le secteur La Balme / Lagnieu. Prévoir un détour hors ViaRhôna et vérifier les routes d’accès.'}];
let route,map,routeLayer,turnMarker,waterGroup,stationGroup,waterPoints=[],weatherData=null,weatherRequest=0;
let turn=store.get('turn',95),tripDate=store.get('date','2026-10-09');
const EARTH=6371,rad=x=>x*Math.PI/180;
function distance(a,b){const h=Math.sin(rad(b[0]-a[0])/2)**2+Math.cos(rad(a[0]))*Math.cos(rad(b[0]))*Math.sin(rad(b[1]-a[1])/2)**2;return EARTH*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function safeDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(new Date(s+'T12:00:00').getTime());}
if(!safeDate(tripDate))tripDate='2026-10-09';turn=Math.max(79,Math.min(115,Number(turn)||95));
function addDays(date,n){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
const formatDate=s=>new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4200);}
function link(url,text){const a=document.createElement('a');a.href=url;a.textContent=text;a.target='_blank';a.rel='noopener';return a;}
function mapsUrl(lat,lon){return `https://www.google.com/maps/search/?api=1&query=${lat},${lon}`;}
async function getJSON(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(18000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
function coordAt(km){const i=route.km.findIndex(d=>d>=km);return route.coordinates[i<0?route.coordinates.length-1:i];}
function pointsTo(km){const i=route.km.findIndex(d=>d>=km);return route.coordinates.slice(0,i<0?undefined:i+1);}
function marker(latlon,text,kind=''){return L.marker(latlon,{icon:L.divIcon({html:`<span class="marker ${kind}">${text}</span>`,className:'',iconSize:[30,30],iconAnchor:[15,15]})});}
function updateDate(){const sunday=addDays(tripDate,2);$('date-help').textContent=`${formatDate(tripDate)} → ${formatDate(sunday)}`;if(new Date(tripDate+'T12:00:00').getDay()!==5)$('date-help').textContent+=' · attention : départ choisi hors vendredi';updatePlan();renderStations();}
function updatePlan(){if(!route)return;const first=route.km[route.segments[2].start];const saturday=2*(turn-first);$('turn-value').textContent=turn+' km';$('totals').innerHTML=`<div><strong>${Math.round(turn*2)} km</strong><span>sur le week-end</span></div><div><strong>2 nuits</strong><span>à confirmer</span></div>`;
const days=[{name:'Vendredi',km:first,title:'Lyon → La Balme',text:'Départ 13 h. Compter environ 4 h de roulage à 16 km/h, plus les pauses. Viser le camp avant 18 h ; raccourcir si le départ ou l’allure le demande.'},{name:'Samedi',km:saturday,title:'Explorer, puis faire demi-tour',text:`Poursuivre jusqu’au km ${turn}, puis revenir autour de La Balme pour la seconde nuit. Demi-tour fixé sur le tracé, à ajuster au terrain et au groupe.`},{name:'Dimanche',km:first,title:'La Balme → Lyon',text:'Départ conseillé vers 9 h. Arrivée visée 16–17 h, pauses comprises, avec de la marge avant la nuit.'}];
$('days').replaceChildren(...days.map((d,i)=>{const el=document.createElement('article');el.className='day';el.innerHTML=`<div class="day-heading"><span>${d.name} · ${new Date(addDays(tripDate,i)+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})}</span><strong>${Math.round(d.km)} km</strong></div><h3>${d.title}</h3><p>${d.text}</p>`;return el;}));
$('route-warning').textContent=saturday>80?'Samedi dépasse 80 km. Pour une première sortie, un demi-tour plus tôt laissera davantage de temps au camp.':'';
if(map){routeLayer.setLatLngs(pointsTo(turn));const c=coordAt(turn);turnMarker.setLatLng(c.slice(0,2));turnMarker.bindPopup(`Demi-tour proposé · km ${turn}<br>Repère sur le GPX, hors vérification du terrain.`);}
renderWater();}
async function initMap(){try{route=await getJSON('data/route.json');if(!window.L)throw Error('Bibliothèque carte indisponible');map=L.map('map',{scrollWheelZoom:false}).setView([45.81,5.1],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
L.polyline(route.coordinates.map(c=>c.slice(0,2)),{color:'#174d57',weight:3,opacity:.25,dashArray:'4 8'}).addTo(map).bindPopup('Suite du tracé officiel vers Groslée');routeLayer=L.polyline(pointsTo(turn).map(c=>c.slice(0,2)),{color:'#087e92',weight:5,opacity:.95,className:'route-flow',dashArray:'14 5'}).addTo(map);
marker(route.coordinates[0].slice(0,2),'D').addTo(map).bindPopup('Départ du GPX · Lyon<br>Ajouter votre trajet pour rejoindre ce point.');const first=route.km[route.segments[2].start];marker(coordAt(first).slice(0,2),'⌂').addTo(map).bindPopup('La Balme-les-Grottes<br>Secteur des deux nuits. Aucun lieu de bivouac autorisé confirmé.');turnMarker=marker(coordAt(turn).slice(0,2),'↶','turn').addTo(map);waterGroup=L.layerGroup().addTo(map);stationGroup=L.layerGroup().addTo(map);
stations.forEach(s=>{const box=document.createElement('div');const strong=document.createElement('strong');strong.textContent='Gare de '+s.name;box.append(strong,document.createElement('br'),document.createTextNode(s.note),document.createElement('br'),link(mapsUrl(s.lat,s.lon),'Voir la gare ↗'));marker([s.lat,s.lon],'T','station').bindPopup(box).addTo(stationGroup);});
map.fitBounds(routeLayer.getBounds(),{padding:[30,35]});$('map-status').textContent='Trait bleu : parcours choisi · pointillé : prolongement vers Groslée · ⌂ secteur des nuits à confirmer';updatePlan();renderWater();
}catch(e){$('map-status').textContent='Carte indisponible. Rechargez en ligne ; les fiches officielles et les GPX restent accessibles ci-dessous.';$('download').disabled=!route;}}
function normalizeWater(raw){return raw.elements.map(e=>({id:e.type+'/'+e.id,lat:e.lat??e.center?.lat,lon:e.lon??e.center?.lon,name:e.tags?.name||'Point d’eau',tags:e.tags||{}})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&p.tags.drinking_water!=='no').map(p=>{let min=Infinity,index=0;route.coordinates.forEach((c,i)=>{const d=distance(c,[p.lat,p.lon]);if(d<min){min=d;index=i;}});return {...p,fromRoute:Math.round(min*1000),km:Math.round(route.km[index]*10)/10};}).filter(p=>p.fromRoute<=2000);}
async function loadWater(refresh=false){$('refresh-water').disabled=true;try{if(!refresh){const cached=store.get('water');if(cached){waterPoints=cached.points;$('water-status').textContent=`${waterPoints.length} points en mémoire · relevé ${cached.retrieved}. Vérifier leur disponibilité sur place.`;renderWater();return;}try{const data=await getJSON('data/water.json');waterPoints=data.points;store.set('water',data);$('water-status').textContent=`${waterPoints.length} points autour du tracé · relevé ${data.retrieved} · ${data.source}.`;renderWater();return;}catch{}}
if(!route)throw Error('Tracé indisponible');$('water-status').textContent='Recherche des points d’eau OpenStreetMap…';const query='[out:json][timeout:15];nwr[amenity=drinking_water](45.67,4.78,45.94,5.53);out center tags;';let data;for(const endpoint of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']){try{data=await getJSON(endpoint+'?data='+encodeURIComponent(query));break;}catch{}}if(!data)throw Error('Serveurs indisponibles');waterPoints=normalizeWater(data);const retrieved=new Date().toLocaleString('fr-FR');store.set('water',{points:waterPoints,retrieved});$('water-status').textContent=`${waterPoints.length} points autour du tracé · actualisés ${retrieved} · © OpenStreetMap contributors.`;renderWater();
}catch{$('water-status').textContent=waterPoints.length?'Actualisation impossible. Les derniers points restent affichés ; vérifiez leur disponibilité.':'Points d’eau indisponibles. Réessayez en ligne. Prévoyez un ravitaillement en village et ne comptez pas sur une fontaine non confirmée.';if(!waterPoints.length){$('water-list').replaceChildren(link('https://www.openstreetmap.org/#map=12/45.81/5.15','Ouvrir OpenStreetMap pour rechercher les fontaines ↗'));}}finally{$('refresh-water').disabled=false;}}
function renderWater(){if(!route)return;const sector=$("water-sector").value;const list=waterPoints.filter(p=>p.km<=turn+1&&(sector==="all"||sector==="lyon"&&p.km<26.7||sector==="balme"&&p.km>=26.7&&p.km<64||sector==="north"&&p.km>=64)).sort((a,b)=>a.km-b.km);$('water-list').replaceChildren();waterGroup?.clearLayers();for(const p of list){const item=document.createElement('article');item.className='water-item';const title=document.createElement('strong');title.textContent=p.name;const desc=document.createElement('small');desc.textContent=`Km ${p.km} · à environ ${p.fromRoute} m à vol d’oiseau du tracé`;const note=document.createElement('small');note.textContent=p.tags.access==='private'?'Accès privé indiqué · autorisation nécessaire':'Point répertorié · fonctionnement à vérifier';const osm=link(p.url||'https://www.openstreetmap.org/'+p.id,p.url?'Fiche du point ↗':'Fiche OSM ↗');const btn=document.createElement('button');btn.textContent='Voir sur la carte';btn.onclick=()=>{if(!map)return toast('Carte indisponible : ouvrir la fiche OSM.');map.setView([p.lat,p.lon],16);document.querySelector('#parcours').scrollIntoView();};item.append(title,desc,note,btn,osm);$('water-list').append(item);if(waterGroup){const popup=document.createElement('div');popup.append(title.cloneNode(true),desc.cloneNode(true),note.cloneNode(true),osm.cloneNode(true));marker([p.lat,p.lon],'●','water').bindPopup(popup).addTo(waterGroup);}}}
function weatherName(code){if(code===0)return 'Ciel dégagé';if(code<=3)return 'Éclaircies / nuages';if(code<=48)return 'Brouillard';if(code<=67)return 'Pluie';if(code<=77)return 'Neige';if(code<=82)return 'Averses';if(code<=86)return 'Averses de neige';return 'Orages';}
function renderWeather(data,cached=false){const d=data.daily;$('weather-cards').replaceChildren();let found=0;for(let n=0;n<3;n++){const day=addDays(tripDate,n),i=d.time.indexOf(day);const card=document.createElement('article');card.className='weather-card';const heading=document.createElement('h3');heading.textContent=formatDate(day);card.append(heading);if(i<0){const p=document.createElement('p');p.textContent='Date hors des prévisions disponibles. Actualisez à l’approche du départ.';card.append(p);}else{found++;const v=key=>d[key]?.[i];const number=(key,suffix='')=>typeof v(key)==='number'?Math.round(v(key))+suffix:'—';const temp=document.createElement('div');temp.className='temperature';temp.innerHTML=`${number('temperature_2m_max','°')} <small>/ ${number('temperature_2m_min','°')} min.</small>`;const sky=document.createElement('p');sky.textContent=weatherName(v('weather_code'));const sunset=v('sunset')?.slice(11,16)||'—';const dl=document.createElement('dl');for(const [label,value] of [['Pluie',number('precipitation_sum',' mm')],['Probabilité pluie',number('precipitation_probability_max',' %')],['Vent max.',number('wind_speed_10m_max',' km/h')],['Rafales max.',number('wind_gusts_10m_max',' km/h')],['Coucher du soleil',sunset]]){const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=value;dl.append(dt,dd);}card.append(temp,sky,dl);} $('weather-cards').append(card);}
$('weather-status').textContent=`${cached?'Dernières prévisions conservées':'Prévisions actualisées'} · ${data.place} · ${data.retrieved}${found?'':' · aucune prévision disponible pour les dates choisies'}`;}
async function loadWeather(){const seq=++weatherRequest;const key=$('weather-place').value,place=places[key];$('refresh-weather').disabled=true;$('weather-status').textContent='Actualisation pour '+place.name+'…';try{const url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:place.lat,longitude:place.lon,timezone:'Europe/Paris',forecast_days:16,daily:'temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,weather_code,wind_speed_10m_max,wind_gusts_10m_max,sunset'});const data=await getJSON(url);if(!data.daily?.time)throw Error('Prévision incomplète');if(seq!==weatherRequest)return;weatherData={...data,place:place.name,retrieved:new Date().toLocaleString('fr-FR')};store.set('weather-'+key,weatherData);renderWeather(weatherData);}catch{if(seq!==weatherRequest)return;const cached=store.get('weather-'+key);if(cached){weatherData=cached;renderWeather(cached,true);$('weather-status').textContent+=' · actualisation indisponible';}else{weatherData=null;$('weather-cards').replaceChildren();$('weather-status').textContent='Prévisions indisponibles. Réessayez en ligne ou consultez Météo-France ci-dessous.';}}finally{if(seq===weatherRequest)$('refresh-weather').disabled=false;}}
function renderStations(){$('station-cards').replaceChildren(...stations.map(s=>{const el=document.createElement('article');el.className='station-card';const h=document.createElement('h3');h.textContent=s.name;const p=document.createElement('p');p.textContent=s.note;const url=new URL('https://www.sncf-connect.com/app/home/search');url.search=new URLSearchParams({origin:s.name,destination:'Lyon Part Dieu',outwardDate:addDays(tripDate,2)+'T14:00:00',adult:'3'});el.append(h,p,link(url.href,'Chercher horaires et prix ↗'),link(mapsUrl(s.lat,s.lon),'Voir la gare ↗'),link('https://www.ter.sncf.com/auvergne-rhone-alpes','Site TER ↗'));return el;}));}
function answer(topic){const answers={next:['Avant le départ : télécharger le GPX, confirmer les deux nuits et consulter météo et passage Jons–Loyettes. Vendredi, privilégier une arrivée au camp avant 18 h. Samedi, repartir vers le nord puis faire demi-tour au repère choisi. Dimanche, quitter le camp vers 9 h.','#parcours','Voir les étapes'],water:[`${waterPoints.filter(p=>p.km<=turn+1).length} points d’eau sont actuellement chargés pour votre parcours. Consultez leurs fiches et vérifiez sur place : une fontaine peut être coupée. Avant le bivouac, remplir aussi la réserve pour cuisiner et repartir le matin.`,'#eau','Voir les points d’eau'],camp:['Les deux nuits sont prévues autour de La Balme, sans emplacement autorisé identifié. Demander l’accord du propriétaire et vérifier les restrictions locales. Choisir un terrain sec en retrait des berges basses. Miribel-Jonage interdit le camping. Enregistrer ici les lieux confirmés.','#bivouac','Préparer les nuits'],return:['Montluel, La Valbonne et Ambérieu sont des options à étudier selon votre position. Les accès aux gares sont hors GPX. Vérifier horaires, prix, travaux et disponibilité pour trois vélos avant de quitter la ViaRhôna. En octobre, vélo annoncé gratuit dans les TER AURA sous réserve de place.','#trains','Voir les options TER'],weather:[`Avec un demi-tour au km ${turn}, vous prévoyez ${Math.round(turn*2)} km au total. Raccourcir le samedi si le groupe fatigue ou si vent et pluie ralentissent. Garder le dimanche à environ 64 km. Pour vendredi, un départ tardif peut imposer une première nuit plus proche. Regarder aussi les minima nocturnes pour le camp.`,'#meteo','Consulter la météo']};const a=answers[topic]||['Je peux vous aider sur l’eau, le bivouac, la météo, les étapes et le retour en train. Choisissez un des boutons ci-dessus pour une réponse adaptée à cette sortie.','#parcours','Voir le parcours'];$('answer').replaceChildren(document.createTextNode(a[0]));const l=document.createElement('a');l.href=a[1];l.textContent=a[2]+' →';$('answer').append(l);}
function downloadGPX(){if(!route)return toast('Le tracé doit être chargé pour exporter le GPX.');const first=route.km[route.segments[2].start];const outward=pointsTo(turn),campIndex=route.km.findIndex(k=>k>=first);const legs=[outward.slice(0,campIndex+1),[...outward.slice(campIndex),...outward.slice(campIndex,-1).reverse()],outward.slice(0,campIndex+1).reverse()];const xml=`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Au fil du Rhône · source ViaRhôna" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>Week-end ViaRhôna · ${tripDate}</name><desc>3 étapes. Nuits et accès domicile hors GPX. Source France Vélo Tourisme / ViaRhôna, relevé 2026-10-08.</desc></metadata>${legs.map((pts,i)=>`<trk><name>Jour ${i+1}</name><trkseg>${pts.map(c=>`<trkpt lat="${c[0]}" lon="${c[1]}"><ele>${c[2]}</ele></trkpt>`).join('')}</trkseg></trk>`).join('')}</gpx>`;const url=URL.createObjectURL(new Blob([xml],{type:'application/gpx+xml'}));const a=document.createElement('a');a.href=url;a.download=`viarhona-weekend-${tripDate}.gpx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('GPX des trois étapes téléchargé.');}
function connection(){const online=navigator.onLine;$('connection').textContent=online?'En ligne':'Hors connexion';if(!online)$('offline-status').textContent='Hors connexion : fiche et GPX en mémoire ; fond de carte et actualisations nécessitent internet.';}
$('turn').value=turn;$('date').value=tripDate;$('turn').addEventListener('input',e=>{turn=Number(e.target.value);store.set('turn',turn);updatePlan();});$('date').addEventListener('change',e=>{if(!safeDate(e.target.value))return;tripDate=e.target.value;store.set('date',tripDate);updateDate();if(weatherData)renderWeather(weatherData,true);});$('download').onclick=downloadGPX;$('fit').onclick=()=>map?map.fitBounds(routeLayer.getBounds(),{padding:[30,35]}):toast('Carte indisponible. Rechargez en ligne.');
$('locate').onclick=()=>{if(!navigator.geolocation)return toast('Géolocalisation indisponible sur cet appareil.');if(!map)return toast('Chargez la carte avant de vous situer.');navigator.geolocation.getCurrentPosition(p=>{const c=[p.coords.latitude,p.coords.longitude];L.circle(c,{radius:p.coords.accuracy,color:'#287c9b',fillOpacity:.12}).addTo(map);L.circleMarker(c,{radius:7,color:'white',weight:3,fillColor:'#287c9b',fillOpacity:1}).addTo(map).bindPopup('Votre position · précision ±'+Math.round(p.coords.accuracy)+' m').openPopup();map.setView(c,14);},()=>toast('Position non accessible. Vérifiez l’autorisation de localisation.'),{timeout:12000,enableHighAccuracy:true});};
$('water-layer').onchange=e=>{if(map&&waterGroup)e.target.checked?waterGroup.addTo(map):map.removeLayer(waterGroup);};$('station-layer').onchange=e=>{if(map&&stationGroup)e.target.checked?stationGroup.addTo(map):map.removeLayer(stationGroup);};$('water-sector').onchange=renderWater;$('refresh-water').onclick=()=>loadWater(true);$('refresh-weather').onclick=loadWeather;$('weather-place').onchange=loadWeather;$('print').onclick=()=>window.print();
for(const id of ['night1','night2','group-note']){$(id).value=store.get(id,'');$(id).oninput=e=>{$('notes-status').textContent=store.set(id,e.target.value)?'Notes enregistrées sur cet appareil.':'Stockage indisponible : copiez vos notes avant de fermer.';};} $('permission').checked=store.get('permission',false);$('permission').onchange=e=>store.set('permission',e.target.checked);document.querySelectorAll('[data-check]').forEach(el=>{el.checked=store.get('check-'+el.dataset.check,false);el.onchange=()=>store.set('check-'+el.dataset.check,el.checked);});document.querySelectorAll('[data-answer]').forEach(el=>el.onclick=()=>answer(el.dataset.answer));$('ask-form').onsubmit=e=>{e.preventDefault();const q=$('question').value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');answer(/eau|bidon|fontaine/.test(q)?'water':/dorm|bivouac|camp|tente|nuit/.test(q)?'camp':/train|ter|gare|retour/.test(q)?'return':/meteo|pluie|vent|froid|fatigue|distance/.test(q)?'weather':/faire|depart|etape|maintenant/.test(q)?'next':'unknown');};
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelectorAll('nav a').forEach(n=>n.classList.remove('active'));a.classList.add('active');});window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();updateDate();
initMap().then(()=>loadWater());loadWeather();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(async reg=>{await navigator.serviceWorker.ready;$('offline-status').textContent='Fiche et GPX prêts hors connexion. Le fond de carte, les nouveaux points d’eau et la météo nécessitent internet.';reg.update();}).catch(()=>$('offline-status').textContent='Mode hors connexion non disponible. Téléchargez les GPX avant le départ.');

if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('main>section').forEach(el=>observer.observe(el));}
